language: java
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "ferzerkerx-github"
    token:
      secure: "kgxWlqC5u382rPr0SnD9R82TIjJfYZ+/S95AAO/r8w2zo1A82N0Y7ZkNr879HhzJ8h4NgSeAolyCOueVt4rYUvDtPpcM1Qoaa0mVXL+De1IeslNkTt0M8QobIE5NthPS5ZOpM55ADuHhcKzTrD0oMxdJdRNHi7gFITDBfVLpstflY4UwfJQI9VpNNSelycyVcwypMM1AF0ENdQ3TZ6tOQRCnI6XCQrpHKApQ4q/6QcFHE6d2HvLWpSEjmT9kMLU4zjlCPFAlKplH+ey69s7IrZXiLmSu3VXIdFwtBP51MYFDG8X83+IKcpiL+fzdwzHduKJ9RZHmBOF+7U4XPmzc+GAk05ayyeSsQJXPsd/pefKLdisc3UHuZqsOR4DCnZHt9aiP7JgTcqJgPyGRVocNLyHDbTcYVKEamw2rOh66rem35VOn2HlfhJ8B38iLPMUufcB64YVcu8da5qdlEhppAs25QpmwVTV2yWKyoDLUyUceQwdbwO5nBV4F+dPM/jElF5l/eDNgCLOmD9yDEP7nrGneRbPmyxt/T6D/tB5oAOL9Gw2VfGunmU7rrqb2EDFxBZ/u/ATAJH9IGJvWmHwNv5QfyKBwdBxyqu/TwA/5py8KMzY4Khjrjx2Ep3rHLBnXLvhk5flk1z5KGBTIYuHFusG/KT9mA8g8l4Px+cyPMEg="
env:
  secure: "iZu462/ig2XtQZoz+bpBtvSrDk2/egQWpLZVBBXgF8R5bHRr0QDLDa5FocgECjOIJRpNTWyMQdlweOn2o9pv0wBsrFj4pkZXsxv/DhrF5pyWydGdejThYbA2NfVy8lO33IZMKRmoBEjOGeAAru95aUTTfHFdzxDscZwvg4k5RaZUdltte+wI5orslZgl/OqL+kNxDI94fsBx5gm97xMyeAe+1OSpmLV8ysEu2vqb3h9qiikKW1Z26rywNF90rMgI1CMZehDVHklxvmRN7ZzvOBVy7CrsLjSVH1wHKaaZSYxSrCtWaKGyGnj8cpSyAv6X7TtH0lzS8RJscBosD3RlfqHnqE+5VWComDa+Xa5kqZzCEgu9LEZBtQzEYeBfgMMytW2Dy2zdTFzHnitsMumQLRC4s52xRd9nJ/w/OpkdEJrtMja8nXSfIIdUOP9XLOayTYf7Z9B6gYKyoq1N9IBMGds0jltIoikDocycVkFrj/2V58QKVw3cmSamJ3ZpysW3O9xDA716loiasPBbP3IPeNlMBsrs1mJFX2+EG3XsvCJvWUMxA5LSzxfDRqZtauf/vEfvC5rWup4P+Mt2t5ouKTDLTcktATQr/HLs3nCQrdFXpX2fcP1z0VaRmxNOvZmkGi4LlPBJEQenqScpwRgJJYFKChyJrlZq+iYy6qJPZP4="

install:
  - "mvn clean compile"
  - "npm install -g snyk"

script:
  - "mvn -Dmaven.test.failure.ignore=false org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar"

after_success:
  - snyk monitor
