language: java
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "ferzerkerx-github"
    token:
      secure: "kgxWlqC5u382rPr0SnD9R82TIjJfYZ+/S95AAO/r8w2zo1A82N0Y7ZkNr879HhzJ8h4NgSeAolyCOueVt4rYUvDtPpcM1Qoaa0mVXL+De1IeslNkTt0M8QobIE5NthPS5ZOpM55ADuHhcKzTrD0oMxdJdRNHi7gFITDBfVLpstflY4UwfJQI9VpNNSelycyVcwypMM1AF0ENdQ3TZ6tOQRCnI6XCQrpHKApQ4q/6QcFHE6d2HvLWpSEjmT9kMLU4zjlCPFAlKplH+ey69s7IrZXiLmSu3VXIdFwtBP51MYFDG8X83+IKcpiL+fzdwzHduKJ9RZHmBOF+7U4XPmzc+GAk05ayyeSsQJXPsd/pefKLdisc3UHuZqsOR4DCnZHt9aiP7JgTcqJgPyGRVocNLyHDbTcYVKEamw2rOh66rem35VOn2HlfhJ8B38iLPMUufcB64YVcu8da5qdlEhppAs25QpmwVTV2yWKyoDLUyUceQwdbwO5nBV4F+dPM/jElF5l/eDNgCLOmD9yDEP7nrGneRbPmyxt/T6D/tB5oAOL9Gw2VfGunmU7rrqb2EDFxBZ/u/ATAJH9IGJvWmHwNv5QfyKBwdBxyqu/TwA/5py8KMzY4Khjrjx2Ep3rHLBnXLvhk5flk1z5KGBTIYuHFusG/KT9mA8g8l4Px+cyPMEg="
env:
  secure: "cIKi46jTfz0B9fs8xaOvLTwk787Sr5F1ZIrQ/b4BgyQ4nyTL2zwOmvISoPL6RHxKPC2jVU6RNGuzzW8hckXKhlxjfSxg689Dnf5HJfRYDZsux7rKQoe0s+wajopiMOJUDRk7iUc1UAu/M/NjBh5eP322/qh5MsLUZVLRxQxB4Kb82yRSK65dDJIFIDyp3gqJG5J13i2tZBREwzEw6PQ3RVCO7xVq4g//IwWh6N72MSN7jh7ETV5d8gdNLQEE3SIxUpU8tdnmhLScYzdFoEb2+GbMWTnqfLQgOLHO+Wn0KPIAuPVmeULChjIaOEHpAgRHPeJlW6ZHqkMV0mWshTwDBVCCbcSKMtdnxTiqzvyYzLEwkBNZkeDdmQ4LhBVpGnY7d9aGC3We+rb3WG7xoNrlYsaorDru8ugTLeH8xqsVU38QRErkWRC2amoEV65W5lSga7QO0u5aMaDEShoXWUdVQPzkYw7zYtpdLYmg8vVqCipZntOxEj+Ujk9WKzcPnkFHE68hUhcSy21JtfPtFU2Zj6qt7KObmD2wpTCjaxXvXMnAZUlEvyXTcI4rv3H+PYwOmIKhTDDXS2gtWbyhL2Wma36Lf9imNI9LRTWocIiSwUkjWLuNy45bTIofplHdyp+2DUTTsWeSXPmMZ+19wshlhfyqzaEyOzq+xPBk+0W7k+E="

install:
  - "mvn clean compile"
  - "npm install -g snyk"

script:
  - "mvn install sonar:sonar"
  - "snyk test"

after_success:
  - snyk monitor